# -*- Mode: Makefile; Modified: "Thu 11 Aug 2005 17:07:57 by dbs"; -*- 

## This makefile builds one or more subdirectories.

## Define the variables needed by Make.example.subdirs

# trace the chain of included makefiles
makefiles += example_AMRPoisson

# relative path to the Chombo "lib" directory
CHOMBO_HOME = ../../lib

# relative paths to the subdirectories to build
exec_dirs = exec

# application-specific variables go here ...

# the shared code for building in example subdirectories
include $(CHOMBO_HOME)/mk/Make.example.subdirs

# application-specific targets go here ...
