# -*- Mode: Makefile; Modified: "Fri 19 Aug 2005 16:03:17 by dbs"; -*- 

## This makefile builds one or more subdirectories.

## Define the variables needed by Make.example.subdirs

# trace the chain of included makefiles
makefiles += example_AMRUpwind

# relative path to the Chombo "lib" directory
CHOMBO_HOME = ../../lib

# relative paths to the subdirectories to build
exec_dirs = exec

# the shared code for building in example subdirectories
include $(CHOMBO_HOME)/mk/Make.example.subdirs

# application-specific variables go here ...

# application-specific targets go here ...
